### ISSUE TITLE
Link zu Package des Moduls Person im Wiki

### ISSUE THREAD

**Issue by Mandalka** [medizininformatik-initiative/kerndatensatz-meta#50]
Der Link zum Package des Moduls Person im Wiki https://github.com/medizininformatik-initiative/kerndatensatz-meta/wiki führt aktuell zum Package des Moduls Diagnose bzw. https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.diagnose/2024.0.0
 
Richtige URL wohl https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.person/2024.0.0

**Comment by julsas** [comment]
Danke @Mandalka ist korrigiert
